Metalord/Assets/_Test/PSC/InputSystem/PlayerAction.cs, Metalord/Assets/_Test/PSC/InputSystem/PlayerAction.inputactions, Metalord/Assets/_Test/PSC/PSCTest.unity, Metalord/Assets/_Test/PSC/PhysicMaterial.meta, Metalord/Assets/_Test/PSC/PhysicMaterial/Player.physicMaterial, Metalord/Assets/_Test/PSC/PhysicMaterial/Player.physicMaterial.meta, Metalord/Assets/_Test/PSC/Scripts/Player/PlayerCollision.cs, Metalord/Assets/_Test/PSC/Scripts/Player/PlayerController.cs, Metalord/Assets/_Test/PSC/Scripts/Player/PlayerValue.cs, Metalord/Assets/_Test/PSC/Scripts/Scriptable/Inputs/PlayerInputReader.asset, Metalord/Assets/_Test/PSC/Scripts/Scriptable/Inputs/PlayerInputReader.asset.meta, Metalord/Assets/_Test/PSC/Scripts/Scriptable/ScriptableBase/Input/InputReader.cs
[박성철 [Add] 플레이어 이동, 점프, 아이템사용 추가]
[박성철 [Feat] 플레이어 기본 이동 구현]
=> 박성철 [Feat] 플레이어 기본 이동 구현

Metalord/Assets/_Test/PSC/PSCTest.unity, Metalord/Assets/_Test/PSC/Scripts/Player/PlayerController.cs, Metalord/Assets/_Test/PSC/Scripts/Player/PlayerValue.cs, Metalord/ProjectSettings/DynamicsManager.asset, Metalord/ProjectSettings/TagManager.asset
[박성철 [Refactor] 키입력 바인딩 위치 변경]
[박성철 [Unity] 레이어 추가, collision매트릭스 수정]
=> 박성철 : 플레이어 코드 리팩토링, 유니티 설정 추가

Metalord/Assets/_Test/KHJ/Prefabs.meta, Metalord/Assets/_Test/KHJ/Scripts.meta, Metalord/Packages/manifest.json, Metalord/Packages/packages-lock.json
유니티 패키지 spline , cinemachine 추가
=> 김형준 : [Unity]  유니티 패키지 spline , cinemachine 추가

Metalord/Assets/_Test/PSC/Materials.meta, Metalord/Assets/_Test/PSC/Materials/FindPopup.mat, Metalord/Assets/_Test/PSC/Materials/FindPopup.mat.meta, Metalord/Assets/_Test/PSC/PSCTest.unity, Metalord/Assets/_Test/PSC/Prefabs.meta, Metalord/Assets/_Test/PSC/Prefabs/Cube (1).prefab, Metalord/Assets/_Test/PSC/Prefabs/Cube (1).prefab.meta, Metalord/Assets/_Test/PSC/Scripts/Item/ItemBaseTest.cs, Metalord/Assets/_Test/PSC/Scripts/Player/PlayerCollision.cs, Metalord/Assets/_Test/PSC/Scripts/Player/PlayerController.cs, Metalord/Assets/_Test/PSC/Scripts/Player/PlayerValue.cs
=> 박성철 플레이어 그랩 시스템 작성중

Metalord/Assets/_Test/PSC/Materials/FindPopup.mat, Metalord/Assets/_Test/PSC/PSCTest.unity, Metalord/Assets/_Test/PSC/Scripts/Item/ItemBaseTest.cs, Metalord/Assets/_Test/PSC/Scripts/Player/GroundCollision.cs, Metalord/Assets/_Test/PSC/Scripts/Player/GroundCollision.cs.meta, Metalord/Assets/_Test/PSC/Scripts/Player/PlayerCollision.cs, Metalord/Assets/_Test/PSC/Scripts/Player/PlayerController.cs, Metalord/Assets/_Test/PSC/Scripts/Player/PlayerValue.cs
[박성철 [Add] 플레이어 컨트롤 수정중]
[박성철 [Add] joint를 사용하여 연결 구현]
=> 박성철 플레이어 구조 작업중

Metalord_btin/MetaLord/Assets/_Test/PSC/Prefabs/Player.prefab, Metalord_btin/MetaLord/Assets/_Test/PSC/Scripts/Input/InputReader.cs, Metalord_btin/MetaLord/Assets/_Test/PSC/Scripts/Player/CameraManager.cs, Metalord_btin/MetaLord/Assets/_Test/PSC/Scripts/Player/Controller_Physics.cs, Metalord_btin/MetaLord/Assets/_Test/SSC/Scripts/SSC_GunState.cs, Metalord_btin/MetaLord/Assets/_Test/SSC/Scripts/SSC_PaintGun.cs, Metalord_btin/MetaLord/ProjectSettings/DynamicsManager.asset, Metalord_btin/MetaLord/ProjectSettings/ProjectSettings.asset, Metalord_btin/MetaLord/ProjectSettings/TagManager.asset
[박성철 [Add] 회전시 끊기는 현상 완화]
[박성철 [Refactor] 플레이어 수치 조정]
[박성철 [Unity] physic Collision Matrix 수정, layer추가]
[박성철 [Add] 플레이어 디테일 추가 (등산중 발사/재장전 제한, 올라갈시에 총 위치 변경)]
=> 박성철 플레이어 디테일 추가

Metalord_btin/MetaLord/Assets/_Test/BKT/Prefabs.meta, Metalord_btin/MetaLord/Assets/_Test/BKT/Prefabs/Canvases.prefab.meta, Metalord_btin/MetaLord/Assets/_Test/BKT/Prefabs/Managers.prefab.meta, Metalord_btin/MetaLord/Assets/_Test/BKT/Prefabs/Test.prefab.meta, Metalord_btin/MetaLord/Assets/_Test/KHJ/Scripts/DialogueSystem/DialogueUI.cs, Metalord_btin/MetaLord/Assets/_Test/KHJ/Scripts/InteractableNpc/InteractUI.cs, Metalord_btin/MetaLord/Assets/_Test/KHJ/Scripts/PlayerInteractNpc.cs, Metalord_btin/MetaLord/Assets/_Test/PSC/Animations/UnEquip.anim.meta, Metalord_btin/MetaLord/Assets/_Test/PSC/Scripts/Player/Animation.meta, Metalord_btin/MetaLord/Assets/_Test/PSC/Scripts/Player/Animation/Behaviour.meta
김형준 : Main Scene에 npc prefab 추가 및 player 에 Interact 관련 스크립트 추가  대화 시작시 플레이어 움직임 제어 DialogueUI 스크립트에 추가 (npc 콜라이더 관련 및 대화 시작시 카메라 회전 및 플레이어 움직임 관련 수정 예정)
=> 김형준 : [Feat] Main Scene에 npc prefab 추가 및 player 에 Interact 관련 스크립트 추가 

Metalord_btin/MetaLord/Assets/ImportAsset/Paintz Free/Demo/Materials/PaintStandard.mat, Metalord_btin/MetaLord/Assets/ImportAsset/Paintz Free/Scripts/Paint.cs, Metalord_btin/MetaLord/Assets/ImportAsset/Paintz Free/Scripts/ParticlePainter.cs, Metalord_btin/MetaLord/Assets/MainLevel/Food_FREE/Materials/Color.mat, Metalord_btin/MetaLord/Assets/MainLevel/LowPolyFoodLite/LowPolyFoodLite_2020.3.0_HDRP_v1.0.unitypackage.meta, Metalord_btin/MetaLord/Assets/MainLevel/LowPolyFoodLite/LowPolyFoodLite_2020.3.0_URP_v1.0.unitypackage.meta, Metalord_btin/MetaLord/Assets/MainLevel/LowPolyInterior/LowPolyInterior_2020.3_HDRP_v1.42.unitypackage.meta, Metalord_btin/MetaLord/Assets/MainLevel/LowPolyInterior/LowPolyInterior_2020.3_URP_v1.42.unitypackage.meta, Metalord_btin/MetaLord/Assets/MainLevel/LowPolyInterior/Materials/LowPolyInterior_MAIN.mat, Metalord_btin/MetaLord/Assets/MainLevel/LowPolyMedievalPropsLite/LowPolyMedievalPropsLite_2020.3.0_HDRP_v1.0.unitypackage.meta, Metalord_btin/MetaLord/Assets/MainLevel/LowPolyMedievalPropsLite/LowPolyMedievalPropsLite_2020.3.0_URP_v1.0.unitypackage.meta, Metalord_btin/MetaLord/Assets/MainLevel/WoodsLifestyle/Models/Vegetation/Flowers/Materials/Leaves_Green_01.mat, Metalord_btin/MetaLord/Assets/MainLevel/polyperfect/Poly Halloween/- Materials/VFX/candle-fire.mat, Metalord_btin/MetaLord/Assets/_Test/SSC/Scripts/SSC_BondGun.cs, Metalord_btin/MetaLord/Assets/_Test/SSC/Scripts/SSC_BondGun.cs.meta, Metalord_btin/MetaLord/Assets/_Test/SSC/Scripts/SSC_BondObj.cs, Metalord_btin/MetaLord/Assets/_Test/SSC/Scripts/SSC_BondObj.cs.meta, Metalord_btin/MetaLord/Assets/_Test/SSC/Scripts/SSC_GrabGun.cs, Metalord_btin/MetaLord/Assets/_Test/SSC/Scripts/SSC_GrabObj.cs, Metalord_btin/MetaLord/Assets/_Test/SSC/Scripts/SSC_GunState.cs, Metalord_btin/MetaLord/Assets/_Test/SSC/Scripts/SSC_PaintGun.cs
[신성창 : [Add] 총 장전중 무기교체 방지, 장전 중 사격방지, 그랩중 무기교체 방지, 장전시간 사용자 설정값 세팅가능]
[신성창 : [Refactor] GunState, GrabGun Update 콜백내부동작 메소드화 처리]
[신성창 : [Add] BondGun, BondObj 스크립트 작성, BondMode 베이스 시스템 설계완료]
=> 신성창 : [Add] 총 장전중 무기교체 방지, 장전 중 사격방지, 그랩중 무기교체 방지, 장전시간 사용자 설정값 세팅가능

Metalord_btin/MetaLord/Assets/MainLevel/LowPolyFoodLite/LowPolyFoodLite_2020.3.0_HDRP_v1.0.unitypackage.meta, Metalord_btin/MetaLord/Assets/MainLevel/LowPolyFoodLite/LowPolyFoodLite_2020.3.0_URP_v1.0.unitypackage.meta, Metalord_btin/MetaLord/Assets/MainLevel/LowPolyInterior/LowPolyInterior_2020.3_HDRP_v1.42.unitypackage.meta, Metalord_btin/MetaLord/Assets/MainLevel/LowPolyInterior/LowPolyInterior_2020.3_URP_v1.42.unitypackage.meta, Metalord_btin/MetaLord/Assets/MainLevel/LowPolyMedievalPropsLite/LowPolyMedievalPropsLite_2020.3.0_HDRP_v1.0.unitypackage.meta, Metalord_btin/MetaLord/Assets/MainLevel/LowPolyMedievalPropsLite/LowPolyMedievalPropsLite_2020.3.0_URP_v1.0.unitypackage.meta, Metalord_btin/MetaLord/Assets/_Test/KHJ/Scenes/KHJ_MainTestScene2.unity.meta, Metalord_btin/MetaLord/Assets/_Test/PSC/Scripts/Player/Controller_Physics.cs
김형준 :  player gun animation 오동작 수정
=> 김형준 : [Fix] player gun animation 오동작 수정

Metalord_btin/MetaLord/Assets/_Test/PSC/Scripts/Player/Controller_Physics.cs, Metalord_btin/MetaLord/Assets/_Test/SSC/Scripts/GrabGun.cs
=> 배경택:[Pull Request] 메인 씬에 적용

Metalord_btin/MetaLord/Assets/_Test/BKT/Scripts/Settings/ReadyMenu.cs, Metalord_btin/MetaLord/ProjectSettings/BurstAotSettings_StandaloneOSX.json
배경택:[Add] 로비 이동 -> 임시 게임 종료로 변경
=> 배경택:[Pull Request] 로비 이동 -> 임시 게임 종료로 변경

Metalord_btin/MetaLord/Assets/MainLevel/LowPolyFoodLite/LowPolyFoodLite_2020.3.0_HDRP_v1.0.unitypackage.meta, Metalord_btin/MetaLord/Assets/MainLevel/LowPolyFoodLite/LowPolyFoodLite_2020.3.0_URP_v1.0.unitypackage.meta, Metalord_btin/MetaLord/Assets/MainLevel/LowPolyInterior/LowPolyInterior_2020.3_HDRP_v1.42.unitypackage.meta, Metalord_btin/MetaLord/Assets/MainLevel/LowPolyInterior/LowPolyInterior_2020.3_URP_v1.42.unitypackage.meta, Metalord_btin/MetaLord/Assets/MainLevel/LowPolyMedievalPropsLite/LowPolyMedievalPropsLite_2020.3.0_HDRP_v1.0.unitypackage.meta, Metalord_btin/MetaLord/Assets/MainLevel/LowPolyMedievalPropsLite/LowPolyMedievalPropsLite_2020.3.0_URP_v1.0.unitypackage.meta, Metalord_btin/MetaLord/Assets/_Test/KHJ/Prefabs/ImportantPrefab/Npc/BabyRoomNpc/RobotRealNPC.prefab, Metalord_btin/MetaLord/Assets/_Test/KHJ/Prefabs/ImportantPrefab/Npc/BabyRoomNpc/RobotRealNPC.prefab.meta, Metalord_btin/MetaLord/Assets/_Test/KHJ/Scenes/KHJ_MainTestScene5.unity.meta, Metalord_btin/MetaLord/Assets/_Test/KHJ/Scenes/KHJ_TestScene6.unity.meta, Metalord_btin/MetaLord/Assets/_Test/KHJ/Scripts/DialogueSystem/DialogueTypingEffect.cs, Metalord_btin/MetaLord/Assets/_Test/KHJ/Scripts/DialogueSystem/DialogueUI.cs
김형준 : [Add] 로봇 메시 합치고 프립팹화 해서 추가
김형준 : [Unity] bear NPC 상호작용 관련 수정 및 다이얼로그 UI 스크립트 삭제예정 주석
=> 김형준 :  bear NPC 상호작용 관련 수정 및 다이얼로그 UI 스크립트 삭제예정 주석

Metalord_btin/MetaLord/Assets/ImportAsset/Paintz Free/Scripts/PaintTarget.cs, Metalord_btin/MetaLord/Assets/_Test/PSC/Scripts/Player/Controller_Physics.cs, Metalord_btin/MetaLord/Assets/_Test/SSC/Scripts/BondGun.cs, Metalord_btin/MetaLord/Assets/_Test/SSC/Scripts/GrabGun.cs, Metalord_btin/MetaLord/Assets/_Test/SSC/Scripts/GunBase.cs, Metalord_btin/MetaLord/Assets/_Test/SSC/Scripts/GunStateController.cs, Metalord_btin/MetaLord/Assets/_Test/SSC/Scripts/PaintGun.cs, Metalord_btin/MetaLord/Assets/_Test/SSC/Scripts/SSC_BondObj.cs, Metalord_btin/MetaLord/Packages/manifest.json, Metalord_btin/MetaLord/Packages/packages-lock.json
[신성창 : [Fix] GrabGun 이동형 오브젝트 플레이 하단에 있을 때 발사 못하게 수정, 그랩중인 오브젝트 플레이 하단에 충돌시 그랩 캔슬되게 수정]
[신성창 : [Add] 재장전시 페인트칠한 게임오브젝트만 초기화하게 수정, 최적화 관련 PaintTarget SphereCastAll 범위 수정]
=> 신성창 : [Fix] GrabGun 이동형 오브젝트 플레이 하단에 있을 때 발사 못하게 수정, 그랩중인 오브젝트 플레이 하단에 충돌시 그랩 캔슬되게 수정

Metalord_btin/MetaLord/Assets/MainLevel/LowPolyFoodLite/LowPolyFoodLite_2020.3.0_HDRP_v1.0.unitypackage.meta, Metalord_btin/MetaLord/Assets/MainLevel/LowPolyFoodLite/LowPolyFoodLite_2020.3.0_URP_v1.0.unitypackage.meta, Metalord_btin/MetaLord/Assets/MainLevel/LowPolyInterior/LowPolyInterior_2020.3_HDRP_v1.42.unitypackage.meta, Metalord_btin/MetaLord/Assets/MainLevel/LowPolyInterior/LowPolyInterior_2020.3_URP_v1.42.unitypackage.meta, Metalord_btin/MetaLord/Assets/MainLevel/LowPolyMedievalPropsLite/LowPolyMedievalPropsLite_2020.3.0_HDRP_v1.0.unitypackage.meta, Metalord_btin/MetaLord/Assets/MainLevel/LowPolyMedievalPropsLite/LowPolyMedievalPropsLite_2020.3.0_URP_v1.0.unitypackage.meta, Metalord_btin/MetaLord/Assets/_Test/KHJ/Scripts/DialogueSystem/DialogueTypingEffect.cs, Metalord_btin/MetaLord/Assets/_Test/KHJ/Scripts/InteractableNpc/InteractUI.cs
김형준 : [Fix] InteractUI 스크립트에서 상호작용 npc 이미지가 player 를 바라보게끔 lookat 메서드 Update에 사용하게끔 수정
및 타이핑 텍스트 에서 wait for second  쓰던 것들 realtime 으로 변경
=> 김형준 : InteractUI 스크립트에서 상호작용 npc 이미지가 player 를 바라보게끔 lookat 메서드 Update에 사용하게끔 수정

Metalord_btin/MetaLord/Assets/_Test/KHJ/Scenes/KHJ_TestTitleScene1.unity, Metalord_btin/MetaLord/Assets/_Test/KHJ/Scripts/DialogueSystem/InteractImageFade.cs, Metalord_btin/MetaLord/Assets/_Test/KHJ/Scripts/TitleScript/OnButtonCheck.cs, Metalord_btin/MetaLord/Assets/_Test/KHJ/Scripts/TitleScript/TextFadeInOut.cs, Metalord_btin/MetaLord/Assets/_Test/KHJ/Scripts/TitleScript/TextFadeInOut.cs.meta
김형준 : [Add] 버튼 위에 올렸을 때 텍스트 폰트 사이즈와 굵기 변경 및 처음 타이틀에서 tmp 페이드 인 아웃 되게끔 추가
=> 김형준 :  버튼 위에 올렸을 때 텍스트 폰트 사이즈와 굵기 변경 및 처음 타이틀에서 tmp 페이드 인 아웃 되게끔 추가

Metalord_btin/MetaLord/Assets/_Test/BKT/Prefabs/Canvases.prefab, Metalord_btin/MetaLord/Assets/_Test/BKT/Scripts/Managers/CoinManager.cs, Metalord_btin/MetaLord/Assets/_Test/BKT/Scripts/Managers/Controller_UI.cs, Metalord_btin/MetaLord/Assets/_Test/BKT/Scripts/Managers/RecordManager.cs, Metalord_btin/MetaLord/Assets/_Test/BKT/Scripts/Settings/ExplainCanvas.cs, Metalord_btin/MetaLord/Assets/_Test/BKT/Scripts/Settings/KeyExplainCanvas.cs, Metalord_btin/MetaLord/Assets/_Test/BKT/Scripts/Store/Store_WeaponStatus.cs, Metalord_btin/MetaLord/Assets/_Test/PSC/Scripts/Player/Controller_Physics.cs
배경택[Pull Request] 메인씬에 UI 변경내용 적용
=> 배경택[Pull Request] 메인씬에 UI 변경내용 적용

Metalord_btin/MetaLord/Assets/MainLevel/LowPolyFoodLite/LowPolyFoodLite_2020.3.0_HDRP_v1.0.unitypackage.meta, Metalord_btin/MetaLord/Assets/MainLevel/LowPolyFoodLite/LowPolyFoodLite_2020.3.0_URP_v1.0.unitypackage.meta, Metalord_btin/MetaLord/Assets/MainLevel/LowPolyInterior/LowPolyInterior_2020.3_HDRP_v1.42.unitypackage.meta, Metalord_btin/MetaLord/Assets/MainLevel/LowPolyInterior/LowPolyInterior_2020.3_URP_v1.42.unitypackage.meta, Metalord_btin/MetaLord/Assets/MainLevel/LowPolyMedievalPropsLite/LowPolyMedievalPropsLite_2020.3.0_HDRP_v1.0.unitypackage.meta, Metalord_btin/MetaLord/Assets/MainLevel/LowPolyMedievalPropsLite/LowPolyMedievalPropsLite_2020.3.0_URP_v1.0.unitypackage.meta, Metalord_btin/MetaLord/Assets/_Test/BKT/Prefabs/Canvases.prefab, Metalord_btin/MetaLord/Assets/_Test/BKT/Scripts/Events/RecordEvents.cs, Metalord_btin/MetaLord/Assets/_Test/BKT/Scripts/Settings/Save/SavingCanvas.cs, Metalord_btin/MetaLord/Assets/_Test/BKT/Scripts/Store/Store_WeaponStatus.cs, Metalord_btin/MetaLord/Assets/_Test/BKT/Scripts/Store/UI_CurrentCoin.cs, Metalord_btin/MetaLord/Assets/_Test/BKT/Scripts/Store/UI_Store.cs
배경택:[Pull Request] 저장 불러오기 오류 수정
=> 배경택:[Pull Request] 저장 불러오기 오류 수정

Metalord_btin/MetaLord/Assets/_Test/KHJ/Prefabs/CombinePrefab/CombineSteak.prefab, Metalord_btin/MetaLord/Assets/_Test/KHJ/Prefabs/CombinePrefab/CombineSteak.prefab.meta, Metalord_btin/MetaLord/Assets/_Test/KHJ/Scenes/KHJ_TestMainScene2.unity.meta, Metalord_btin/MetaLord/Assets/_Test/KHJ/Scenes/KHJ_TestMainScene3.unity.meta
김형준 : [Add] 스테이크 오브젝트 팬과 합친 후 프리팹화
=> 김형준 : 스테이크 오브젝트 팬과 합친 후 프리팹화

Metalord_btin/MetaLord/Assets/MeshExtractorSettings.asset, Metalord_btin/MetaLord/Assets/_Test/BKT/Scripts/Store/StoreObject.cs, Metalord_btin/MetaLord/Assets/_Test/KHJ/Scripts/InteractableNpc/NpcBase.cs, Metalord_btin/MetaLord/Assets/_Test/PSC/Animations/Player.controller, Metalord_btin/MetaLord/Assets/_Test/PSC/Scripts/Player/Controller_Physics.cs, Metalord_btin/MetaLord/ProjectSettings/QualitySettings.asset
[박성철 [Add] 플레이어 조작감 조정 중]
[박성철 [Add] 그림자 추가]
=> 박성철 플레이어 조작감 조정, 그림자 추가

Metalord_btin/MetaLord/Assets/_Test/KHJ/Prefabs/CombinePrefab/CombineCupSpoon.prefab, Metalord_btin/MetaLord/Assets/_Test/KHJ/Prefabs/CombinePrefab/CombineCupSpoon.prefab.meta
김형준 : [Fix] Main Scene 묶어야할 컵과 스푼 합친 후 교체 및 npc 상호작용 canvas 레이어 수정
=> 김형준 : Main Scene 묶어야할 컵과 스푼 합친 후 교체 및 npc 상호작용 canvas 레이어 수정

Metalord_btin/MetaLord/Assets/_Test/BKT/Scripts/Loading/LoadingController.cs, Metalord_btin/MetaLord/Assets/_Test/BKT/Scripts/ReadyMenu/ReadyMenu.cs, Metalord_btin/MetaLord/Assets/_Test/PSC/Scripts/Manager/SoundManager.cs, Metalord_btin/MetaLord/ProjectSettings/Packages/com.unity.probuilder/Settings.json
배경택:[Add] 메인씬 변경사항(환경설정) 적용, 로비로 돌아가기 적용
=> 배경택:[Pull Request] 메인씬 변경사항(환경설정) 적용, 로비로 돌아가기 적용

Metalord_btin/MetaLord/Assets/MainLevel/MainScene/LoadingScene.unity, Metalord_btin/MetaLord/Assets/_Test/BKT/Scripts/Managers/CoinManager.cs, Metalord_btin/MetaLord/Assets/_Test/BKT/Scripts/Managers/DataManager.cs, Metalord_btin/MetaLord/Assets/_Test/BKT/Scripts/Managers/GameEventsManager.cs, Metalord_btin/MetaLord/Assets/_Test/BKT/Scripts/Managers/MainSceneManager.cs, Metalord_btin/MetaLord/Assets/_Test/BKT/Scripts/Managers/RecordManager.cs, Metalord_btin/MetaLord/Assets/_Test/BKT/Scripts/ReadyMenu/ReadyMenu.cs, Metalord_btin/MetaLord/Assets/_Test/BKT/Scripts/ReadyMenu/Settings/DisplaySetting.cs, Metalord_btin/MetaLord/Assets/_Test/BKT/Scripts/ReadyMenu/Settings/ResolutionSetting.cs, Metalord_btin/MetaLord/Assets/_Test/KHJ/Scripts/TitleController.cs, Metalord_btin/MetaLord/Assets/_Test/PSC/Scripts/Manager/SoundManager.cs
=> 배경택:[Pull Request] 오류 해결

Metalord_btin/MetaLord/Assets/MainLevel/MainScene/LoadingScene.unity, Metalord_btin/MetaLord/Assets/MainLevel/MainScene/StoryScene.unity, Metalord_btin/MetaLord/Assets/MainLevel/MainScene/TitleScene.unity, Metalord_btin/MetaLord/Assets/_Test/BKT/Scripts/Loading/StartInfo.cs, Metalord_btin/MetaLord/Assets/_Test/BKT/Scripts/Managers/AudioManager.cs, Metalord_btin/MetaLord/Assets/_Test/BKT/Scripts/ReadyMenu/Explain/KeyExplainCanvas.cs, Metalord_btin/MetaLord/Assets/_Test/BKT/Scripts/ReadyMenu/ReadyMenu.cs, Metalord_btin/MetaLord/Assets/_Test/BKT/Scripts/TitleScene/AnySceneBrightness.cs, Metalord_btin/MetaLord/Assets/_Test/BKT/Scripts/TitleScene/AnySceneBrightness.cs.meta, Metalord_btin/MetaLord/Assets/_Test/PSC/Scripts/Story/StorySceneManager.cs, Metalord_btin/MetaLord/ProjectSettings/Packages/com.unity.probuilder/Settings.json
배경택:[Pull Request] 타이틀씬, 로딩씬, 스토리씬, 메인 씬 개인설정 연동 구성
=> 배경택:[Pull Request] 타이틀씬, 로딩씬, 스토리씬, 메인 씬 개인설정 연동 구성

Metalord_btin/MetaLord/Assets/_Test/BKT/Prefabs/Canvases.prefab, Metalord_btin/MetaLord/Assets/_Test/BKT/Scripts/Loading/LoadingController.cs, Metalord_btin/MetaLord/Assets/_Test/BKT/Scripts/Managers/Controller_UI.cs, Metalord_btin/MetaLord/Assets/_Test/KHJ/Scripts/TitleController.cs
UI : 글자 크기 증가시 2줄로 넘어가던 오류 수정
오디오 : 게임 재시작시 스토리 씬에서 오디오가 두개 실행되는 오류 수정
=> 배경택:[Pull Request] UI, 오디오 오류 해결 및 Main Scene 수정

Metalord_btin/MetaLord/Assets/MainLevel/MainScene/TitleScene.unity, Metalord_btin/MetaLord/Assets/_Test/BKT/Prefabs/Canvases.prefab, Metalord_btin/MetaLord/Assets/_Test/BKT/Scripts/Loading/LoadingController.cs, Metalord_btin/MetaLord/Assets/_Test/BKT/Scripts/Loading/StartInfo.cs, Metalord_btin/MetaLord/Assets/_Test/BKT/Scripts/Managers/DataManager.cs, Metalord_btin/MetaLord/Assets/_Test/BKT/Scripts/Managers/MainSceneManager.cs, Metalord_btin/MetaLord/Assets/_Test/BKT/Scripts/Managers/RecordManager.cs, Metalord_btin/MetaLord/Assets/_Test/BKT/Scripts/ReadyMenu/Settings/BrightnessSetting.cs, Metalord_btin/MetaLord/Assets/_Test/BKT/Scripts/ReadyMenu/Settings/KeyRebind/RebindKeyUI.cs, Metalord_btin/MetaLord/Assets/_Test/BKT/Scripts/ReadyMenu/Settings/VolumeSetting.cs, Metalord_btin/MetaLord/Assets/_Test/BKT/Scripts/Store/UI_Store.cs, Metalord_btin/MetaLord/Assets/_Test/BKT/Scripts/Test/Test.cs, Metalord_btin/MetaLord/Assets/_Test/BKT/Scripts/Test/Test.cs.meta, Metalord_btin/MetaLord/Assets/_Test/BKT/Scripts/TitleScene/AnySceneBrightness.cs, Metalord_btin/MetaLord/Assets/_Test/KHJ/Scripts/TitleController.cs, Metalord_btin/MetaLord/Assets/_Test/PSC/Scripts/Input/InputReader.cs, Metalord_btin/MetaLord/Assets/_Test/PSC/Settings/InputSystem/PlayerInputActions.cs, Metalord_btin/MetaLord/Assets/_Test/PSC/Settings/InputSystem/PlayerInputActions.inputactions, Metalord_btin/MetaLord/ProjectSettings/InputManager.asset
배경택:[Pull Request] 키 리바인딩, 게임 불러오기 오류 수정
=> 배경택:[Pull Request] 키 리바인딩, 게임 불러오기 오류 수정

Metalord_btin/MetaLord/Assets/_Test/BKT/Prefabs/Canvases.prefab
배경택:[Pull Request] NPC 상호작용 리바인드 UI 삭제
=> 배경택:[Pull Request] NPC 상호작용 리바인드 UI 삭제

Metalord_btin/MetaLord/Assets/MeshExtractorSettings.asset, Metalord_btin/MetaLord/Assets/_Test/BKT/Prefabs/Canvases.prefab, Metalord_btin/MetaLord/Assets/_Test/KHJ/Prefabs/FixPrefab/FixRugbyBall.prefab, Metalord_btin/MetaLord/Assets/_Test/SSC/Prefabs/BakedObject/535Counter_01_BKT.prefab, Metalord_btin/MetaLord/Assets/_Test/SSC/Prefabs/BakedObject/535Counter_01_BKT.prefab.meta, Metalord_btin/MetaLord/Assets/_Test/SSC/Prefabs/BakedObject/flower345_SSC.prefab, Metalord_btin/MetaLord/ProjectSettings/Packages/com.unity.probuilder/Settings.json
배경택:[Pull Request] 메인씬 텍스쳐가 깨져있는 오브젝트 텍스처 수정
=> 배경택:[Pull Request] 메인씬 텍스쳐가 깨져있는 오브젝트 텍스처 수정

Metalord_btin/MetaLord/Assets/_Test/SSC/Scenes/SSC_MainScene.unity.meta, Metalord_btin/MetaLord/Assets/_Test/SSC/Scripts/CatchObject.cs, Metalord_btin/MetaLord/Assets/_Test/SSC/Scripts/GrabGun.cs, Metalord_btin/MetaLord/Assets/_Test/SSC/Scripts/GunBase.cs, Metalord_btin/MetaLord/Assets/_Test/SSC/Scripts/MovedObject.cs
[신성창 : [Fix] GrabGun 공중에서 오브젝트 놨두는 현상 수정, 오브젝트 겹치는 부분에서 오브젝트 종속 모호성 생기 는 부분 파악중]
[신성창 : [Fix] 양방향 페인팅 체크용 트리거 그랩한 오브젝트에서만 동작하도록 수정(오브젝트 겹치는 구간 방어기제용)]
=> 신성창 : [Fix] GrabGun 공중에서 오브젝트 놨두는 현상 수정]

Metalord_btin/MetaLord/Assets/_Test/BKT/Scripts/Managers/MainSceneManager.cs, Metalord_btin/MetaLord/Assets/_Test/BKT/Scripts/Managers/RecordManager.cs, Metalord_btin/MetaLord/Assets/_Test/BKT/Scripts/Record/RecordItem.cs, Metalord_btin/MetaLord/Assets/_Test/BKT/Scripts/Record/RecordPopUpCanvas.cs
=> 배경택:[Pull Request] 게임 엔딩 추가

Metalord_btin/MetaLord/Assets/_Test/KHJ/Animations/EndingCanvas/EndingCanvas.anim
김형준 : [Fix] 애니메이션 Fade In Out 시간 늘리기
=> 김형준 : 애니메이션 Fade In Out 시간 늘리기

Metalord_btin/MetaLord/Assets/_Test/BKT/Scripts/Managers/RecordManager.cs, Metalord_btin/MetaLord/Assets/_Test/BKT/Scripts/ReadyMenu/Settings/DisplaySetting.cs, Metalord_btin/MetaLord/Assets/_Test/BKT/Scripts/ReadyMenu/Settings/KeyRebind/RebindKeyUI.cs, Metalord_btin/MetaLord/Assets/_Test/BKT/Scripts/ReadyMenu/Settings/KeyRebind/ResetKeyBindings.cs, Metalord_btin/MetaLord/Assets/_Test/BKT/Scripts/ReadyMenu/Settings/TextSizeSetting.cs, Metalord_btin/MetaLord/Assets/_Test/BKT/Scripts/ReadyMenu/Settings/VolumeSetting.cs, Metalord_btin/MetaLord/Assets/_Test/BKT/Scripts/Record/RecordItem.cs, Metalord_btin/MetaLord/Assets/_Test/BKT/Scripts/Record/RecordObject.cs, Metalord_btin/MetaLord/Assets/_Test/BKT/Scripts/Record/RecordPopUpCanvas.cs, Metalord_btin/MetaLord/Assets/_Test/BKT/Scripts/Record/UI_Sort.cs
배경택:[Fix] 불러오기시 도감 엔딩조건 초기화 안되는 오류 해결
=> 배경택:[Pull Request] 불러오기시 도감 엔딩조건 초기화 안되는 오류 해결

Metalord_btin/MetaLord/Assets/_Test/KHJ/Scripts/VideoPlayTest.cs
배경택:[Fix] AudioSource Null 예외사항 해결
=> 배경택:[Pull Request] AudioSource Null 예외사항 해결
